find codeword= 06 (len = 3) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 04 (len = 3) in huffman tree
find codeword= 04 (len = 3) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 04 (len = 3) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 1c (len = 5) in huffman tree
find codeword= 1c (len = 5) in huffman tree
find codeword= 1c (len = 5) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 3a (len = 6) in huffman tree
find codeword= 0a (len = 4) in huffman tree
find codeword= 05 (len = 3) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 04 (len = 3) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 1b (len = 5) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 1fa (len = 9) in huffman tree
find codeword= 0a (len = 4) in huffman tree
find codeword= 05 (len = 3) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 1c (len = 5) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 7f9 (len = 11) in huffman tree
find codeword= 7b (len = 7) in huffman tree
find codeword= 0a (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 04 (len = 3) in huffman tree
find codeword= 04 (len = 3) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 0c (len = 4) in huffman tree
find codeword= 1c (len = 5) in huffman tree
find codeword= 1c (len = 5) in huffman tree
find codeword= 7f8 (len = 11) in huffman tree
find codeword= 0a (len = 4) in huffman tree
find codeword= 0e (len = 4) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 04 (len = 3) in huffman tree
find codeword= 1a (len = 5) in huffman tree
find codeword= 00 (len = 2) in huffman tree
find codeword= 02 (len = 2) in huffman tree
find codeword= 04 (len = 3) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 0b (len = 4) in huffman tree
find codeword= 01 (len = 2) in huffman tree
find codeword= 00 (len = 2) in huffman tree
